# Generated by Django 2.1.3 on 2019-01-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.FileField(blank=True, upload_to='postimage/%y/%m/%d')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
