# Generated by Django 2.1.3 on 2019-01-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='date',
        ),
    ]
